### ISSUE TITLE
提个问题，大佬有做增量学习这块吗？

### ISSUE THREAD

**Issue by jinweiisgreat** [buxihuo/unknown-yolo#10]
Incremental learning 应该是Open Wold问题中的一个子模块，想知道作者是如何进行增量学习的

**Comment by buxihuo** [comment]
> 

你好，我目前只做了让检测器说不知道，但是可以不降低原分类的性能。本来准备在其他方向（图像分类、实例分割等）做尝试，但由于导师的一些原因，这几个月一直没有进展，增量学习也没做。
