### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by WangRongsheng** [buxihuo/unknown-yolo#2]
使用您提供的预训练权重预测会出现
```python
IndexError: list index out of range
```

请问：
1. 所提供的权重是基于coco还是voc训练的？
2. 是否可以提供下与权重相搭配的yaml配置文件？

**Comment by buxihuo** [comment]
> 使用您提供的预训练权重预测会出现
> 
> ```python
> IndexError: list index out of range
> ```
> 
> 请问：
> 
> 1. 所提供的权重是基于coco还是voc训练的？
> 2. 是否可以提供下与权重相搭配的yaml配置文件？

1. 我都有训，传的是coco的
2. 数组越界是因为网络输出除了80类还有一个未知类，可以在detect函数做相关处理，我刚开始没改yaml文件，导致需要对第81类处理，如果使用81类的yaml训练则不用处理detect函数。
3. 等忙完最近的事情，我会更新代码
