### ISSUE TITLE
缺少loss文件

### ISSUE THREAD

**Issue by sunnytt98** [buxihuo/unknown-yolo#7]
作者您好，utils文件夹中好像缺少了loss函数。

**Comment by buxihuo** [comment]
您好，我现在在几种训练方案中选择，实验完成后会陆续更新简要说明和代码。但会有些慢，因为我被学校的一些事给拖住了，同时还得找工作。

**Comment by shining-love** [comment]
> 您好，我现在在几种训练方案中选择，实验完成后会陆续更新简要说明和代码。但会有些慢，因为我被学校的一些事给拖住了，同时还得找工作。

完善了这个repo，还愁找不到工作么。。。
